# -*- coding: utf-8 -*-
"""BigData_TugasKelompok_llxyuan-distilbert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12VTJMVtDOkRsZylnGJ1rjP8DATepuIHz

## Local Inference on GPU
Model page: https://huggingface.co/lxyuan/distilbert-base-multilingual-cased-sentiments-student

⚠️ If the generated code snippets do not work, please open an issue on either the [model repo](https://huggingface.co/lxyuan/distilbert-base-multilingual-cased-sentiments-student)
			and/or on [huggingface.js](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/model-libraries-snippets.ts) 🙏
"""

!pip install -U transformers
!pip install datasets
!pip install pandas
!pip install scikit-learn
!pip install openpyxl
!pip install torch

import pandas as pd

df = pd.read_excel("DataGabungan.xlsx")

df.head()

df = df[["Isi komentar", "Sentimen"]]

df = df.rename(columns={
    "Isi komentar": "text",
    "Sentimen": "label"
})

df.head()

df["label"].value_counts()

# Gunakan .replace() lebih aman daripada .map() untuk menghindari nilai NaN
df["label"] = df["label"].replace({
    -1: 0,
    0: 1,
    1: 2
})

df["label"].value_counts()

from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained(
    "lxyuan/distilbert-base-multilingual-cased-sentiments-student"
)

model = AutoModelForSequenceClassification.from_pretrained(
    "lxyuan/distilbert-base-multilingual-cased-sentiments-student",
)

df = df.dropna(subset=["text"])
df = df[df["text"].str.strip() != ""]

df["text"] = df["text"].astype(str)

df.head()

from sklearn.model_selection import train_test_split

train_texts, test_texts, train_labels, test_labels = train_test_split(
    df["text"].tolist(),
    df["label"].tolist(),
    test_size=0.2,
    random_state=42
)

train_encodings = tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=128
)

test_encodings = tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=128
)

import torch

class SentimentDataset(torch.utils.data.Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = SentimentDataset(train_encodings, train_labels)
test_dataset = SentimentDataset(test_encodings, test_labels)

print(f"Total data: {len(df)}")
print(f"Train: {len(train_texts)}")
print(f"Test: {len(test_texts)}")

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=6,          # tambah epoch
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    warmup_steps=500,             # tambahkan warmup
    weight_decay=0.01,            # tambahkan regularisasi
    load_best_model_at_end=True,  # simpan model terbaik
)

# Tambahkan cell ini sebelum WeightedTrainer
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.array([0, 1, 2]),
    y=train_labels
)
print(class_weights)

import torch
from transformers import Trainer

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")
        weights = torch.tensor(class_weights, dtype=torch.float).to(logits.device)
        loss_fn = torch.nn.CrossEntropyLoss(weight=weights)
        loss = loss_fn(logits, labels)
        return (loss, outputs) if return_outputs else loss

trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

trainer.train()

from sklearn.metrics import classification_report
import numpy as np

predictions = trainer.predict(test_dataset)

preds = np.argmax(predictions.predictions, axis=1)

print(classification_report(test_labels, preds))